version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: lyonbank-db-container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: lyonbank-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: