# ==========================================
# PRODUCTION CONFIGURATION (Render/Docker)
# ==========================================

# 1. Database (Injected by render env vars)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# 2. JPA / Hibernate safer settings for prod
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# 3. Security Keys
rsa.private-key=file:/app/certs/private.pem
rsa.public-key=file:/app/certs/public.pem